Online-Tic-Oto/Controllers/FaturaController.cs
using Antlr.Runtime;
using Online_Tic_Oto.Models.AppContext;
using Online_Tic_Oto.Models.Sınıflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Online_Tic_Oto.Controllers
{
    public class FaturaController : Controller
    {
        // GET: Fatura

        Context db = new Context();
        public ActionResult Index()
        {
            var fatlist = db.Faturalars.ToList();

            return View(fatlist);
        }


        [HttpGet]


        public ActionResult FaturaEkle()
        {
            return View();
        }


        [HttpPost]


        public ActionResult FaturaEkle(Faturalar f)
        {
            db.Faturalars.Add(f);

            db.SaveChanges();
            return RedirectToAction("FaturaKalemEkle");
        }


        public ActionResult FaturaGetir(int id)
        {

            var fatgetr = db.Faturalars.Find(id);

            return View("FaturaGetir", fatgetr);
        }

        public ActionResult FaturaGüncelle(Faturalar f)
        {

            var fatgetr = db.Faturalars.Find(f.FaturaID);

            fatgetr.VeriDariesi = f.VeriDariesi;
            fatgetr.Tarih = f.Tarih;
            fatgetr.Saat = f.Saat;
            fatgetr.TeslimEden = f.TeslimEden;
            fatgetr.TeslimAlan = f.TeslimAlan;
            db.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult FaturaDetay(int id)
        {
            var fatdty = db.FaturaKalems.Where(a => a.FaturaID == id).ToList();






            var fatdytbaslk = db.Faturalars.Where(a => a.FaturaID == id).Select(a => a.FaturaSeriNo).FirstOrDefault();
            var fatdytbaslk2 = db.Faturalars.Where(a => a.FaturaID == id).Select(b => b.FaturaSıraNo).FirstOrDefault();

            var baslk1 = fatdytbaslk.ToUpper();

            ViewBag.dft = baslk1 + "  " + fatdytbaslk2;


            return View(fatdty);

        }


        [HttpGet]

        public ActionResult FaturaKalemEkle()

        {
            return View();

        }

        //public ActionResult FaturaKalemEkle(int id)

        //{
        //    FaturaKalem faturaKalem = db.FaturaKalems.FirstOrDefault(a => a.FatureKalemID == id);

        //    var fatura = db.Faturalars.FirstOrDefault(b => b.FaturaID == faturaKalem.FaturaID);

        //    var baslik1 = fatura.FaturaSeriNo.ToUpper();
        //    var baslik2 = fatura.FaturaSıraNo;

        //    //var det2 = db.FaturaKalems.Where(a => a.FatureKalemID == id).Select(a => a.FaturaID).FirstOrDefault();

        //    //var det3 = db.Faturalars.Where(a => a.FaturaID == fat).Select(a => a.FaturaSeriNo).FirstOrDefault();
        //    //var det4 = db.Faturalars.Where(a => a.FaturaID == fat).Select(a => a.FaturaSıraNo).FirstOrDefault();

        //    //var baslik1 = det3.ToUpper();
        //    //var baslik2 = det4;

        //    ViewBag.dft2 = baslik1 + "  " + baslik2;

        //    return View("FaturaKalemEkle");


        //}


        public ActionResult FaturaKalemEkle(FaturaKalem ft)

        {
            db.FaturaKalems.Add(ft);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Online-Tic-Oto/Views/Fatura/FaturaDetay.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<FaturaKalem>
@{
    ViewBag.Title = "FaturaDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Detay </h2>
<br />
<ol class="breadcrumb mb-4" style="background-color: #f2f2f2; border-radius:10px; padding:10px;">
    <li class="breadcrumb-item active" style="margin-left:10px;">   Fatura No: @ViewBag.dft</li>
</ol>
<table class="table table-hover">
    <tr>
        <th>Fatura Açıklama</th>
        <th>Miktar</th>
        <th>Birim Fiyat</th>
        <th>Tutar</th>      
    </tr>
    @foreach (var a in Model)
    {
        <tr>
            <td>@a.FaturaAciklama</td>
            <td>@a.Miktar</td>
            <td>@a.BirimFiyat</td>
            <td>@a.Tutar</td>            
        </tr>
    }
</table>
<a href="/Fatura/FaturaKalemEkle" class="btn btn-primary">Yeni Kalem Giriş</a>

Online-Tic-Oto/Views/Fatura/FaturaEkle.cshtml
@model Online_Tic_Oto.Models.Sınıflar.Faturalar
@{
    ViewBag.Title = "FaturaEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Fatura Girişi </h2>
<br />
<form class="form-group" method="post">
    <label>Seri No</label>
    @Html.TextBoxFor(a => a.FaturaSeriNo, new { @class = "form-control" })
    <br />
    <label>Sıra No</label>
    @Html.TextBoxFor(a => a.FaturaSıraNo, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(a => a.Tarih, new { @class = "form-control" })
    <br />
    <label>Saat</label>
    @Html.TextBoxFor(a => a.Saat, new { @class = "form-control" })
    <br />
    <label>Vergi Dairesi</label>
    @Html.TextBoxFor(a => a.VeriDariesi, new { @class = "form-control" })
    <br />
    <label>Teslim Eden</label>
    @Html.TextBoxFor(a => a.TeslimEden, new { @class = "form-control" })
    <span id="deparmanerror" style="color: red;"></span>
    <br />
    <label>Teslim Alan</label>
    @Html.TextBoxFor(a => a.TeslimAlan, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(document).ready(function () {


        // Tarih alanına jQuery UI Datepicker'ı bağlama
        $("#Tarih").datepicker({
            dateFormat: 'dd.mm.yy', // Tarih formatı
            changeMonth: true,      // Ay seçiciyi göster
            changeYear: true,       // Yıl seçiciyi göster
        });


    });
</script>

Online-Tic-Oto/Views/Fatura/FaturaGetir.cshtml
@model Online_Tic_Oto.Models.Sınıflar.Faturalar
@{
    ViewBag.Title = "FaturaGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
    .form-title {
        font-size: 24px;
    }
</style>
<br />
<h2>Fatura Güncelleme</h2>
<br />
@using (Html.BeginForm("FaturaGüncelle", "Fatura", FormMethod.Post))
{
    @Html.HiddenFor(a => a.FaturaID)
    <div class="row">
        <div class="col-md-2">
            <h4>Fatura Seri No </h4>
        </div>
        <div class="col-md-1">
            <h4>@Html.DisplayFor(a => a.FaturaSeriSiraBirlesik, new { @class = "form-control" })</h4>
        </div>
    </div>
    <br />
    <label>Vergi Dairesi</label>
    @Html.TextBoxFor(a => a.VeriDariesi, new { @class = "form-control" })
    <br />
    <label>Tarih</label>
    @Html.TextBoxFor(a => a.Tarih, "{0:dd.MM.yyyy}", new { @class = "form-control" })
    <br />
    <label>Saat</label>
    @Html.TextBoxFor(a => a.Saat, new { @class = "form-control" })
    <br />
    <label>Teslim Eden</label>
    @Html.TextBoxFor(a => a.TeslimEden, new { @class = "form-control" })
    <br />
    <label>Teslim Alan</label>
    @Html.TextBoxFor(a => a.TeslimAlan, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>

}


<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(document).ready(function () {


        // Tarih alanına jQuery UI Datepicker'ı bağlama
        $("#Tarih").datepicker({
            dateFormat: 'dd.mm.yy', // Tarih formatı
            changeMonth: true,      // Ay seçiciyi göster
            changeYear: true,       // Yıl seçiciyi göster
        });


    });
</script>

Online-Tic-Oto/Views/Fatura/FaturaKalemEkle.cshtml
@model Online_Tic_Oto.Models.Sınıflar.FaturaKalem
@{
    ViewBag.Title = "FaturaKalemEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Fatura Kalem Girişi </h2>
<br />
<form class="form-group" method="post">
    <ol class="breadcrumb mb-4" style="background-color: #f2f2f2; border-radius:10px; padding:10px;">
        <li class="breadcrumb-item active" style="margin-left:10px;">   Fatura No düzenle: @ViewBag.dft2</li>
    </ol>
    <label>Fatura Seri</label>
    @Html.DisplayFor(a => a.FaturaID, new { @class = "form-control" })
    <br />
    <br />
    <br />
    <button type="button" class="btn btn-success add-row">Yeni Satır Ekle</button>
    <button class="btn btn-info">Satış</button>


    <table class="table">
        <thead>
            <tr>
                <th>Açıklama</th>
                <th>Miktar</th>
                <th>Birim Fiyat</th>
                <th>Toplam Tutar</th>
                <th>Fatura ID</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="sale-row">
                <td>
                    @Html.TextBoxFor(a => a.FaturaAciklama, new { @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(a => a.Miktar, new { @class = "form-control" })
                <td>
                    @Html.TextBoxFor(a => a.BirimFiyat, new { @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(a => a.Tutar, new { @class = "form-control" })
                </td>
                <td>
                    @Html.TextBoxFor(a => a.FaturaID, new { @class = "form-control" })
                </td>
                <td>
                    <button type="button" class="btn btn-danger remove-row">Satırı Sil</button>
                </td>
            </tr>
            <!-- Kullanıcı daha fazla ürün satışı eklemek istediğinde yeni satırlar ekleyebilirsiniz -->
        </tbody>
    </table>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        // Yeni satır eklemek için düğme
        $('.add-row').click(function () {
            var newRow = $('tbody tr.sale-row:first').clone();
            newRow.find('input').val('');
            newRow.find('.total-amount').val('0.00');
            $('tbody').append(newRow);
        });

        // Satırı silmek için düğme
        $('tbody').on('click', '.remove-row', function () {
            var rows = $('tbody tr.sale-row');
            if (rows.length === 1) {
                alert('Son satırı silemezsiniz.');
            } else {
                $(this).closest('tr').remove();
            }
        });

        $('tbody').on('input', '.quantity-input, .price-input', function () {
            var row = $(this).closest('tr');
            var quantity = parseFloat(row.find('.quantity-input').val()) || 0;
            var price = parseFloat(row.find('.price-input').val()) || 0;
            var total = quantity * price;
            row.find('.total-amount').val(total.toFixed(2));
        });
    });
</script>

Online-Tic-Oto/Views/Fatura/index.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Faturalar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h4>Fatura Listesi</h4>
<br />
<a href="/Fatura/FaturaEkle" class="btn btn-primary">Yeni Fatura</a>
<br />
<table class="table table-bordered" style="margin-top:20px;">

    <tr>
        <th>ID</th>
        <th>Seri No</th>
        <th>Sıra No</th>
        <th>Vergi Dairese</th>
        <th>Tarih</th>
        <th>Saat</th>
        <th>Teslim Eden</th>
        <th>Teslim Alan</th>
        <th>Toplam</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

    @foreach (var k in Model)
    {
        if (!string.IsNullOrEmpty(k.FaturaSeriNo))
        {
            <tr>
                <td>@k.FaturaID</td>
                <td>@k.FaturaSeriNo</td>
                <td>@k.FaturaSıraNo</td>
                <td>@k.VeriDariesi</td>
                <td>@k.Tarih.ToString("dd.MM.yyyy")</td>
                <td>@k.Saat</td>
                <td>@k.TeslimEden</td>
                <td>@k.TeslimAlan</td>
                <td>@k.ToplamTutar</td>
                <td><a href="/Fatura/FaturaGetir/@k.FaturaID" class="btn btn-success">Güncelle</a></td>
                <td><a href="/Fatura/FaturaDetay/@k.FaturaID" class="btn btn-success" style="background-color:dimgrey">Detay</a></td>

            </tr>
        }

    }



</table>