Online-Tic-Oto/Controllers/İstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using Online_Tic_Oto.Models.AppContext;
using Online_Tic_Oto.Models.Sınıflar;


namespace Online_Tic_Oto.Controllers
{
    public class İstatistikController : Controller
    {
        // GET: İstatistik


        Context db = new Context();
        public ActionResult Index()
        {

            var deger1 = db.Carilers.Count().ToString();
            ViewBag.d1 = deger1;

            var deger2 = db.Uruns.Count().ToString();
            ViewBag.d2 = deger2;

            var deger3 = db.Personels.Count().ToString();
            ViewBag.d3 = deger3;

            var deger4 = db.Kategoris.Count().ToString();
            ViewBag.d4 = deger4;



            var deger5 = db.Uruns.Sum(a => a.Stok).ToString();
            ViewBag.d5 = deger5;

            var deger6 = (from x in db.Uruns select x.Marka).Distinct().Count().ToString();
            ViewBag.d6 = deger6;

            var deger7 = db.Uruns.Count(a => a.Stok <= 20).ToString();
            ViewBag.d7 = deger7;

            var deger8 = (from x in db.Uruns orderby x.SatisFiyat descending select x.UrunAD).FirstOrDefault();
            ViewBag.d8 = deger8;



            var deger9 = (from x in db.Uruns orderby x.SatisFiyat ascending select x.UrunAD).FirstOrDefault();
            ViewBag.d9 = deger9;

            var deger10 = db.Uruns.Where(a => a.UrunAD.Contains("Buzdolabı")).ToList();
            ViewBag.d10 = deger10.Count();

            var deger11 = db.Uruns.Where(a => a.UrunAD.Contains("laptop")).ToList();
            ViewBag.d11 = deger11.Count();

            var deger12 = db.Uruns.GroupBy(a => a.Marka).OrderByDescending(a => a.Count()).Select(a => a.Key).FirstOrDefault();
            ViewBag.d12 = deger12;





            var deger13 = db.Uruns.Where(b => b.UrunID == (db.SatisHarakets.GroupBy(a => a.UrunID).OrderByDescending(a => a.Count()).Select(a => a.Key).FirstOrDefault())).Select(k => k.UrunAD).FirstOrDefault();
            ViewBag.d13 = deger13;

            var deger14 = db.SatisHarakets.Sum(a => a.ToplamTutar).ToString();
            ViewBag.d14 = deger14;


            DateTime buguntarih = DateTime.Today;

            var deger15 = db.SatisHarakets.Count(a => a.Tarih == buguntarih).ToString();
            ViewBag.d15 = deger15;

            //var deger16 = db.SatisHarakets.Where(a => a.Tarih == buguntarih).Sum(a => a.ToplamTutar).ToString();
            var deger16 = db.SatisHarakets.Where(a => a.Tarih == buguntarih).Sum(a => (decimal?)a.ToplamTutar) ?? 0M;

            
                ViewBag.d16 = deger16;


            return View();
        }


        public ActionResult KolayTablolar()
        {

            var sorgu = from c in db.Carilers
                        join s in db.Sehirlers on c.SehirID equals s.SehirID
                        group c by s.SehirADı into g
                        select new GrupSinif
                        {
                            Sehir = g.Key,
                            Sayi = g.Count()
                        };

            return View(sorgu.ToList());
        }

        public PartialViewResult Partial1()
        {
            var sorgu2 = from a in db.Personels
                         join d in db.Departmen on a.DepartmanID equals d.DepartmanID
                         group new { a, d } by a.DepartmanID into g
                         select new GrupSinif2
                         {
                             Departman = g.Key,
                             DepartmanAdi = g.FirstOrDefault().d.DepartmanADI, // Departman adını buradan alıyoruz
                             Sayi = g.Count()
                         };

            return PartialView(sorgu2.ToList());
        }

        public PartialViewResult Partial2()
        {

            var sorgu2 = db.Carilers.ToList();
            return PartialView(sorgu2);
        }

        public PartialViewResult Partial3()
        {

            var sorgu3 = db.Uruns.ToList();
            return PartialView(sorgu3);
        }
        public PartialViewResult Partial4()
        {
            var sorgu4 = from a in db.Uruns                         
                         group a by a.Marka into g
                         select new GrupSinif3
                         {
                             Marka = g.Key,
                             Sayi = g.Count()
                         };
            return PartialView(sorgu4);
        }
    }
}

Online-Tic-Oto/Views/İstatistik/KolayTablolar.cshtml
@model  IEnumerable<Online_Tic_Oto.Models.Sınıflar.GrupSinif>
@{
    ViewBag.Title = "KolayTablolar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hızlı Bakış Tabloları</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Hızlı Bakış Tabloları</h1>
                    </div>
                    
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Kategori</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Kategori</th>
                                            <th>Progress</th>
                                            <th style="width: 40px">Oran</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>Beyaz Eşya</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-danger">55%</span></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Küçük Ev Aletleri</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Bilgisayar</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-primary">30%</span></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Mobilya</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-success">90%</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer clearfix">
                                <ul class="pagination pagination-sm m-0 float-right">
                                    <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- /.card -->
                        <br />
                        @Html.Action("Partial1", "İstatistik")
                        <!-- /.card -->
                    </div>
                    <br />
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Müşteri Şehirleri</h3>


                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Şehir</th>
                                            <th>Progress By</th>
                                            <th style="width: 40px">Adet</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{int sırano = 0; }
                                        @foreach (var a in Model)
                                        {
                                            <tr>
                                                <td>@{sırano++;}@sırano</td>
                                                <td>@a.Sehir</td>
                                                <td>
                                                    @if (a.Sayi >= 1 && a.Sayi <= 10)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 11 && a.Sayi <= 20)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 21 && a.Sayi <= 30)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar accent-red" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 31 && a.Sayi <= 40)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-blue" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 41 && a.Sayi <= 50)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 51 && a.Sayi <= 60)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 61 && a.Sayi <= 70)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }
                                                    @if (a.Sayi >= 71 && a.Sayi <= 81)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    }

                                                </td>
                                                <td><span class="badge bg-danger">@a.Sayi</span></td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                            <div class="card-footer clearfix">
                                <ul class="pagination pagination-sm m-0  float-right">
                                    <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                                </ul>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <br />
                        <!-- /.card -->
                        @Html.Action("Partial4","İstatistik")
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <br />
                </div>
                <!-- /.row -->
                @Html.Action("Partial2", "İstatistik")
                <!-- /.row -->
               @Html.Action("Partial3","İstatistik")
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
        <!-- /.content-wrapper -->
       

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src=".~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

Online-Tic-Oto/Views/İstatistik/Partial1.cshtml
@model  IEnumerable<Online_Tic_Oto.Models.Sınıflar.GrupSinif2>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Sayı</th>
                </tr>
            </thead>
            <tbody>
                @{int sırano = 0; }
                @foreach (var a in Model)
                {
                    <tr>
                        <td>@{sırano++;}@sırano</td>
                        <td>@a.DepartmanAdi</td>
                        <td>
                            @if (a.Sayi >= 1 && a.Sayi <= 10)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 11 && a.Sayi <= 20)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 21 && a.Sayi <= 30)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar accent-red" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 31 && a.Sayi <= 40)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-blue" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 41 && a.Sayi <= 50)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 51 && a.Sayi <= 60)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 61 && a.Sayi <= 70)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 71 && a.Sayi <= 81)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }

                        </td>
                        <td><span class="badge bg-danger">@a.Sayi</span></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

Online-Tic-Oto/Views/İstatistik/Partial2.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Cariler>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Adı Soyadı</th>
                            <th>Şehir</th>
                            <th>Mail</th>                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var a in Model)
                        {
                            <tr>
                                <td>@a.CariID</td>
                                <td>@a.CariADI @a.CariSoyadı</td>
                                <td>@a.Sehirler.SehirADı</td>                               
                                <td>@a.CariMail</td> 
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

Online-Tic-Oto/Views/İstatistik/Partial3.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Urun>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürünler Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Marka</th>
                            <th>Stok</th>
                            <th>Alış Fiyat</th>
                            <th>Satış Fiyat</th>
                        </tr>
                    </thead>
                    <tbody>                       
                        @foreach (var a in Model)
                        {
                            <tr>                                
                                <td>@a.UrunID</td>
                                <td>@a.UrunAD</td>
                                <td>@a.Marka</td>
                                <td>@a.Stok</td>
                                <td>@a.AlisFiyat</td>
                                <td>@a.SatisFiyat</td>
                                

                               
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

Online-Tic-Oto/Views/İstatistik/Partial4.cshtml
@model  IEnumerable<Online_Tic_Oto.Models.Sınıflar.GrupSinif3>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Ürün Marka Tablosu</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Marka</th>
                    <th>Progress Bar</th>
                    <th style="width: 40px">Toplam</th>
                </tr>
            </thead>
            <tbody>
                @{int sırano = 0; }
                @foreach (var a in Model)
                {
                    <tr>
                        <td>@{sırano++;}@sırano</td>
                        <td>@a.Marka</td>
                        <td>
                            @if (a.Sayi >= 1 && a.Sayi <= 10)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 11 && a.Sayi <= 20)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-warning" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 21 && a.Sayi <= 30)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar accent-red" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 31 && a.Sayi <= 40)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg-blue" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 41 && a.Sayi <= 50)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar bg" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 51 && a.Sayi <= 60)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 61 && a.Sayi <= 70)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }
                            @if (a.Sayi >= 71 && a.Sayi <= 81)
                            {
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                </div>
                            }

                        </td>
                        <td><span class="badge bg-danger">@a.Sayi</span></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>