Online-Tic-Oto/Controllers/YapilacakController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Tic_Oto.Models.AppContext;
using Online_Tic_Oto.Models.Sınıflar;

namespace Online_Tic_Oto.Controllers
{
    public class YapilacakController : Controller
    {
        // GET: Yapilacak


        Context db = new Context();
        public ActionResult Index()
        {
            var deger1 = db.Carilers.Count().ToString();
            ViewBag.d1 = deger1;

            var deger2 = db.Uruns.Where(a => a.Durum == true && a.Stok > 0).Count().ToString();
            ViewBag.d2 = deger2;


            var deger3 = db.Kategoris.Count().ToString();
            ViewBag.d3 = deger3;

            var deger4 = (from a in db.Carilers select a.Sehirler.SehirADı).Distinct().Count().ToString();
            ViewBag.d4 = deger4;



            var yapilacaklar = db.Yapılacaklars.Where(a => a.YapDurum == false).ToList();


            DateTime suAnkiTarih = DateTime.Now;

            // Liste içerisindeki her bir yapılacak görevin bitiş tarihini güncelle
            foreach (var yapilacak in yapilacaklar)
            {
                if (yapilacak.bitisTarih != null) // Bitiş tarihi null değilse işlem yap
                {
                    // Bitiş tarihini al
                    DateTime bitisTarihi = yapilacak.bitisTarih;

                    // Şu anki tarihten çıkararak kalan süreyi hesapla
                    TimeSpan kalanSure = bitisTarihi - suAnkiTarih;
                    int süre;

                    string süre2;
                    if (kalanSure.TotalDays >= 1)
                    {


                        // Kalan süre 1 günden fazla ise, gün cinsinden göster
                        süre = (int)kalanSure.TotalDays;
                        string saat = "Gün";
                         süre2 = süre.ToString() +" "+ saat;
                    }
                    else
                    {
                        // Kalan süre 1 günden az ise, saat cinsinden göster
                        süre = (int)kalanSure.TotalHours;

                        string saat = "Saat";
                        süre2 = süre.ToString()+" "+ saat;
                    }

                    string saatli =

                    // Yapılacak görevin kalan süresini KalanSure özelliğine ata
                    yapilacak.KalanSure = süre2;

                }
            }



            return View(yapilacaklar);



        }

        [HttpPost]
        public ActionResult Kapat(List<Yapılacaklar> model)
        {
            if (model != null)
            {
                // model içindeki YapID ve YapDurum bilgilerini kullanarak veritabanını güncelleyin
                foreach (var yap in model)
                {
                    // YapID'yi kullanarak veritabanındaki ilgili kaydı bulun ve YapDurum'u güncelleyin
                    // Örnek: Veritabanı işlemleri


                    var deger = db.Yapılacaklars.Find(yap.YapID);

                    deger.YapDurum = true;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            // İşlem tamamlandıktan sonra başka bir sayfaya yönlendirme yapabilirsiniz
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GorevEkle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult GorevEkle(Yapılacaklar yap)
        {

            if (yap.BaslangicTarih==null)
            {
                yap.BaslangicTarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            }

            

            db.Yapılacaklars.Add(yap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Online-Tic-Oto/Views/Yapilacak/GorevEkle.cshtml
@model Online_Tic_Oto.Models.Sınıflar.Yapılacaklar
@{
    ViewBag.Title = "GorevEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Gorev Ekle</h2>
<br />
<form class="form-group" method="post">
    <label>Görev Başlığı</label>
    @Html.TextBoxFor(a => a.YapBaslik, new { @class = "form-control" })
    <br />
    <label>Göre Detayı</label>
    @Html.TextAreaFor(a => a.YapDetay, new { @class = "form-control" })
    <br />   
    <label>Bitiş Tarihi</label>
    @Html.TextBoxFor(a => a.bitisTarih, "{0:dd.MM.yyyy}", new { @class = "form-control" })
    <br />
    <label>Başlangıc Tarihi</label>
    @Html.TextBoxFor(a => a.BaslangicTarih, "{0:dd.MM.yyyy}", new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(document).ready(function () {


        // Tarih alanına jQuery UI Datepicker'ı bağlama
        $("#bitisTarih").datepicker({
            dateFormat: 'dd.mm.yy', // Tarih formatı
            changeMonth: true,      // Ay seçiciyi göster
            changeYear: true,       // Yıl seçiciyi göster
        });
        $("#BaslangicTarih").datepicker({
            dateFormat: 'dd.mm.yy', // Tarih formatı
            changeMonth: true,      // Ay seçiciyi göster
            changeYear: true,       // Yıl seçiciyi göster
        });

    });
</script>

Online-Tic-Oto/Views/Yapilacak/Index.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Yapılacaklar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!DOCTYPE html>
<br />
<h2>Yeni Personel </h2>
<br />
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
   
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/jqvmap/jqvmap.min.css">
   
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
   
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/daterangepicker/daterangepicker.css">
   
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
   
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">



</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>@ViewBag.d1</h3>

                                <p>Toplam Cari Sayısı</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="~/Cariler/index" class="small-box-footer">Liste İçin <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>@ViewBag.d4</h3>

                                <p>Şehir Sayısı</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a class="small-box-footer"> <label></label></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>@ViewBag.d2</h3>

                                <p>Topam Ürün Sayısı</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="/Urun/index" class="small-box-footer">Liste İçin <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3>@ViewBag.d3</h3>

                                <p>Toplam Kategori Sayısı</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="/Kategori/index" class="small-box-footer">Liste İçin <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                </div>
                <!-- /.row -->
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-lg-7 connectedSortable">

                        <!-- TO DO List -->
                        @using (Html.BeginForm("Kapat", "Yapilacak", FormMethod.Post))
                        {
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="ion ion-clipboard mr-1"></i>
                                        Yapılacak işler
                                    </h3>
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    <ul class="todo-list" data-widget="todo-list">
                                        @for (int i = 0; i < Model.Count; i++)
                                        {
                                            <li>
                                                <!-- drag handle -->
                                                <span class="handle">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </span>
                                                <!-- checkbox -->
                                                <div class="icheck-primary d-inline ml-2">
                                                    @Html.HiddenFor(model => model[i].YapID) <!-- YapID'yi gizli alan olarak ekleyin -->
                                                    @Html.CheckBoxFor(model => model[i].YapDurum, new { id = $"todoCheck{i}" })
                                                    <label for="todoCheck1"></label>
                                                </div>
                                                <!-- todo text -->
                                                <span class="text">@Model[i].YapBaslik Detay: @Model[i].YapDetay</span>
                                                <!-- Emphasis label -->
                                                <small class="badge badge-danger"><i class="far fa-clock"></i> @Model[i].KalanSure </small>
                                                <!-- General tools such as edit or delete-->
                                                <div class="tools">
                                                    <i class="fas fa-edit"></i>
                                                    <i class="fas fa-trash-o"></i>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer clearfix">
                                    <button type="submit" class="btn btn-info float-left"><i class="fas fa-plus"></i> Kapat</button>
                                    <a href="/Yapilacak/GorevEkle" class="btn btn-info float-right"><i class="fas fa-plus"></i>Görev Ekle</a>                                   
                                </div>
                            </div>
                        }
                        <!-- /.card -->
                    </section>

                </div>

            </div><!-- /.container-fluid -->
        </section>

    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>$.widget.bridge('uibutton', $.ui.button)</script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    @*<script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>*@  


    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>


</body>
</html>
<script>
    // Sayfa yüklendiğinde işaretli checkbox'ları gizlemek için bu işlemi kullanabilirsiniz
    window.onload = function () {
        // Tüm checkbox öğelerini alın
        var checkboxes = document.querySelectorAll('input[type="checkbox"]');

        // Her bir checkbox için kontrol yapın
        checkboxes.forEach(function (checkbox) {
            if (!checkbox.checked) {
                // Checkbox işaretsizse, ilgili öğeyi gizle
                var itemId = checkbox.getAttribute('data-item-id');
                var listItem = document.querySelector('#todoCheck-' + itemId).closest('li');
                listItem.style.display = 'none';
            }
        });
    }
</script>