Online-Tic-Oto/Models/Sınıflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Online_Tic_Oto.Models.Sınıflar
{
    public class Departman
    {



        public Departman()
        {
            Durum = true;
        }
        [Key]
        public int DepartmanID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string DepartmanADI { get; set; }

        public bool Durum { get; set; } = true;


        public ICollection<Personel> Personels { get; set; }
    }
}

Online-Tic-Oto/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Tic_Oto.Models.AppContext;
using Online_Tic_Oto.Models.Sınıflar;

namespace Online_Tic_Oto.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context db = new Context();
        public ActionResult Index()
        {
            var degerler = db.Departmen.Where(a => a.Durum == true).ToList();

            return View(degerler);

        }


        [HttpGet]

        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            db.Departmen.Add(d);
            db.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult DepartmanSil(int id)
        {
            var deger = db.Departmen.Find(id);

            deger.Durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult DepartmanGetir(int id)
        {
            List<SelectListItem> departmanList = db.Departmen
             .Select(k => new SelectListItem
             {
                 Value = k.DepartmanID.ToString(),
                 Text = k.DepartmanADI
             })
             .ToList();

            ViewBag.Departmanlar = departmanList;
            var departmanDeger = db.Departmen.Find(id);

            return View("DepartmanGetir",departmanDeger);
        }
        public ActionResult DepartmanGuncelle(Departman k)
        {
            var depgtr = db.Departmen.Find(k.DepartmanID);
            depgtr.DepartmanADI = k.DepartmanADI;         
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult DepartmanDetay(int id)

        {
            var depDty = db.Personels.Where(a=> a.DepartmanID == id).ToList();

            var departBaslk = db.Departmen.Where(a => a.DepartmanID == id).Select(a => a.DepartmanADI).FirstOrDefault();
            ViewBag.d=departBaslk;


            return View(depDty);
           // return RedirectToAction("/Index");
        }

        public ActionResult DepartmanPersonelSatis(int id)
        {

            var degerlr=db.SatisHarakets.Where(a=> a.PesonelID== id).ToList();
             
             var persBaslk=db.Personels.Where(a=> a.PesonelID==id).Select(a=> a.PersonelAD +" "+ a.PersonelSoyad).FirstOrDefault();
            ViewBag.d_pers=persBaslk;
            return View(degerlr);
        }
    }
}

Online-Tic-Oto/Views/Departman/DepartmanDetay.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>

<br />
<h2>Departman Detay </h2>
<br />
<ol class="breadcrumb mb-4" style="background-color: #f2f2f2; border-radius:10px; padding:10px;">
    <li class="breadcrumb-item active" style="margin-left:10px;">   Departman Adı: @ViewBag.d</li>
</ol>
<table class="table table-hover">
    <tr>
        <th>Personel ID</th>
        <th>Adı</th>
        <th>Soyadı</th>
        <th>Görsel</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var a in Model)
    {
        <tr>
            <td>@a.PesonelID</td>
            <td>@a.PersonelAD</td>
            <td>@a.PersonelSoyad</td>
            <td>@a.PersonelGorsel</td>
            <td><a href="/Departman/DepartmanPersonelSatis/@a.PesonelID" class="btn btn-outline-secondary">Satış Detay</a></td>
        </tr>
    }
</table>

Online-Tic-Oto/Views/Departman/DepartmanEkle.cshtml
@model Online_Tic_Oto.Models.Sınıflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Departman </h2>
<br />
<form class="form-group" method="post">
    <label>Departman Adı</label>
    @Html.TextBoxFor(a=> a.DepartmanADI, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

Online-Tic-Oto/Views/Departman/DepartmanGetir.cshtml
@model Online_Tic_Oto.Models.Sınıflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2> Departman GÜncelle </h2>
<br />
@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        <label>Departman Adı</label>
        @Html.TextBoxFor(a => a.DepartmanADI, new { @class = "form-control" })
        @Html.HiddenFor(a => a.DepartmanID)
    </div>
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

Online-Tic-Oto/Views/Departman/DepartmanPersonelSatis.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<SatisHaraket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Personel Satis</h2>
<br />
<ol class="breadcrumb mb-4" style="background-color: #f2f2f2; border-radius:10px; padding:10px;">
    <li class="breadcrumb-item active" style="margin-left:10px;">   Personel Adı: @ViewBag.d_pers</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var a in Model)
    {
        <tr>
            <td>@a.SatisID</td>
            <td>@a.Urun.UrunAD</td>
            <td>@a.Cariler.CariADI @a.Cariler.CariSoyadı</td>
            <td>@a.Adet</td>
            <td>@a.Fiyat</td>
            <td>@a.ToplamTutar</td>
            <td>@a.Tarih.ToString("dd.MM.yyyy")</td>
            <td><a href="#" class="btn btn-primary btn-sm" >Yazdır</a></td>
        </tr>
    }

</table>

Online-Tic-Oto/Views/Departman/index.cshtml
@using Online_Tic_Oto.Models.Sınıflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h4>Departman Listesi</h4>
<table class="table table-bordered" style="margin-top:20px;">

    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>

    @foreach (var k in Model)
    {
        if (!string.IsNullOrEmpty(k.DepartmanADI))
        {
            <tr>
                <td>@k.DepartmanID</td>
                <td>@k.DepartmanADI</td>
                <td><a href="#" class="btn btn-danger" onclick="confirmDelete('@k.DepartmanID')">Sil</a></td>
                <td><a href="/Departman/DepartmanGetir/@k.DepartmanID" class="btn btn-success">Güncelle</a></td>
                <td><a href="/Departman/DepartmanDetay/@k.DepartmanID" class="btn btn-success" style="background-color:dimgrey">Detay</a></td>

            </tr>
        }

    }



</table>
<a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>
<script>
    function confirmDelete(DepartmanID) {
        if (confirm('Bu Departman silmek istediğinize emin misiniz?')) {
            // Kullanıcı "Evet" dediğinde silme işlemini gerçekleştirin
            window.location.href = '/Departman/DepartmanSil/' + DepartmanID;
        }
    }
</script>